### ISSUE TITLE
Some errors with my settings

### ISSUE THREAD

**Issue by lexieD** [danielpereztr/DCEtool#2]
When I use these settings：
Design settings 
Number of attributes:  6 
Levels per attribute:  3 3 3 3 3 2 
Alternatives per choice set:  2 
Number of sets:  18 
Null alternative:  TRUE 
Bayesian priors:  FALSE 
Priors:  0 0 0 0 0 0 0 0 0 0 0 0 
Seed:  9999

I got：

Warning: Error in seq_len: argument must be coercible to non-negative integer
  99: renderUI
  98: func
  85: renderFunc
  84: output$dynamic
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>

**Comment by danielpereztr** [comment]
Hi. Thanks for using DCEtool. 

Your settings seem correct, so probably there is an error in the optimization function. This means that there is not an easy fix at this moment. I'll try to fix it as soon as posible. Thanks for reporting the problem.

**Comment by danielpereztr** [comment]
fyi, a new release has been uploaded to github :)
