### ISSUE TITLE
Nested design

### ISSUE THREAD

**Issue by Gia89** [danielpereztr/DCEtool#4]
Hi Daniel!
I was looking for DCE and I came across your tool! Nice job!

As I got it, at the moment there is not the possibility to construct a nested design, is that correct?

I read the article of Fifrer 2020 (see attached) where they considered a nested design. I have to conduct a similar experiments, where the levels of an attribute depends on the level of the previous one.

Do you think is possible to add this possibility to your tool?

Thanks,
Gianni

[fifer2020.pdf](https://github.com/danielpereztr/DCEtool/files/11556658/fifer2020.pdf)

**Comment by danielpereztr** [comment]
Hi. 

Sadly it does not allow this option and I would need to study it first to include it in the app. I read the paper and I saw they mentioned this nested design, but they did no referenced it. I guess it's an option in the Ngene software (which is somehow related to profs. Rose and Bliemer, who are one of the leading experts in DCEs in the world), so I would assume it is a good practise. 

As I see it, you have three options now: 1) simplifying the design by combining and omitting attributes and levels, 2) buying Ngene, although this might not be an option for many people, 3) have a look at the 'idefix' R package. I do not know if they contemplated this nested design, but I now they have options like omitting certain combinations. The authors did an awesome job in that package, and you should have a look at it.

**Comment by Gia89** [comment]
Hi Daniel,

thanks for you answer. I will definetly have a look at the 'idefix' R package.

Best regards,
Gianni
