### ISSUE TITLE
Error when performing the results analysis

### ISSUE THREAD

**Issue by alinerasilva** [danielpereztr/DCEtool#5]
Hi,
I have some results for a choice-based conjoint analysis and I tried to analyse the results in the DCE tool, however, it does not analyse and gives me an error.

> DCEtool::DCEtool()
Loading required namespace: shinythemes
Loading required namespace: mvtnorm
Loading required namespace: writexl
Loading required namespace: readxl
Loading required namespace: idefix
Loading required namespace: tidyr
Loading required namespace: mlogit
Loading required package: shiny

Listening on http://127.0.0.1:3151
Warning: Error in Surv: could not find function "Surv"
  3: runApp
  2: print.shiny.appobj
  1: <Anonymous>

I have installed everything that was necessary and always gives me the same error, I tried to use a different computer and still the same error. 
Is there anything I should do?

**Comment by danielpereztr** [comment]
Hi. I think Surv is a function from the 'survival' package. It is included in DCEtool, so I don't know what's the problem. In any case, try first with install.packages("survival") and library(survival) and then run DCEtool. If that does not solve the problem, try with other computer or other version of R. If you give me more info abuot your computer or R version maybe I can help.

**Comment by alinerasilva** [comment]
Hi.
I already have the survival package installed. But I just found out that if I run library(survival) first and the run the DCE tool, I can run the results.

**Comment by danielpereztr** [comment]
Yes, my bad, sorry for that. Probably I did not call the package before calling the function in the code. I just uploaded a new version, try with the new version and let me now if the problem persists. Just do install.packages("DCEtool") again.
